name: 'Jira Ticket Assigner'
description: 'Automatically adds jira tickets by scanning the branch name and adding them as a comment to the PR'
author: 'Steven Masala & Shavaun MacArthur'
inputs:
  jira-url:
    description: 'Jira url domain'
  project-prefixes:
    description: 'Comma-separated ticket prefixes such as MYPROJ in MYPROJ-1234'
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: 'clipboard'
  color: 'blue'
