name: 'Jira Ticket Assigner'
description: 'Automatically adds jira tickets by scanning the branch name and adding them as a comment to the PR'
author: 'Steven Masala'
inputs:
  repo-token:              # change this
    description: 'Repo token'
    default: ${{ github.token }}
  jira-url:
    description: 'Jira url domain'
  project-prefix:
    description: 'Ticket prefix such as MYPROJ in MYPROJ-1234'
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: 'clipboard'
  color: 'blue'
